[project]
name = "greed-spider"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "requests>=2.32.3",
]

[project.scripts]
spider = "greed_spider:main"